wip openssl config
infinyon/k8-api pull request #110
Opened 2021-11-05 17:48 UTC by simlay

2021-11-05 18:43 UTC, sehz requested changes
Looks good.  A minor changes is needed to make sure error are feature dependent

2021-11-05 18:43 UTC, sehz commented on src/k8-client/src/error.rs
> +    Tls(fluvio_future::openssl::TlsError),
This is  feature flag dependent

2021-11-06 16:31 UTC, simlay commented on src/k8-client/src/error.rs
> +    Tls(fluvio_future::openssl::TlsError),
done.

2021-11-06 16:34 UTC, sehz approved these changes
LGTM.

2021-11-06 16:42 UTC, sehz commented
rebase fun

2021-11-06 17:47 UTC, sehz commented
bors r+

2021-11-06 17:55 UTC, closed without merging