Remove PascalCase as it's the default option
infinyon/k8-api pull request #111
Opened 2021-11-08 20:33 UTC by qrilka

This is a very minor improvement, it was already proposed in https://github.com/infinyon/k8-api/pull/94#issuecomment-946159404

2021-11-08 21:31 UTC, sehz requested changes
Can you bump up patch version?

2021-11-09 18:54 UTC, qrilka commented
Done

2021-11-09 18:56 UTC, sehz approved these changes
LGTM.  Thank!

2021-11-09 18:56 UTC, sehz commented
bors r+

2021-11-09 19:08 UTC, closed without merging