Config improvements
infinyon/k8-api pull request #123
Opened 2021-11-26 20:55 UTC by qrilka

Added while working on #119

2021-11-26 22:01 UTC, sehz requested changes

2021-11-26 22:01 UTC, sehz commented on src/k8-config/Cargo.toml
> +version = "1.4.1"
Since this adds new capability and fields, let's bump this to `1.5.0`

2021-11-26 22:01 UTC, sehz commented on src/k8-client/Cargo.toml
> +version = "5.3.1"
bump this to `5.4.0` as well

2021-11-27 10:35 UTC, qrilka commented on src/k8-client/Cargo.toml
> +version = "5.3.1"
done

2021-11-27 15:29 UTC, sehz approved these changes
LGTM.  Thanks

2021-11-27 15:29 UTC, sehz commented
bors r+

2021-11-27 15:38 UTC, closed without merging