Add gcp support
infinyon/k8-api pull request #166
Opened 2022-05-09 17:47 UTC by tjtelan

Fixes panic during kubernetes config parse due to cluster use with auth provider and dynamic tokens (like in GCP)
  - Only support for token refresh support via exec of CLI command in auth provider named `gcp`

Add support for GCP kubernetes (GKE) clusters
  - Tested w/ Autopilot and Standard clusters

2022-05-10 18:22 UTC, sehz commented
Can you assign to issue?

2022-05-10 21:30 UTC, sehz requested changes

2022-05-10 21:30 UTC, sehz commented on src/k8-client/src/cert.rs
> +                            debug!("{gcp_auth:#?}");
can you ensure that secrete keys and other auth is not logged?

2022-05-10 21:30 UTC, sehz commented on src/k8-client/src/cert.rs
> +                                .expect("gcp command failed");
turn into error instead of panicking

2022-05-10 21:30 UTC, sehz commented on src/k8-client/src/cert.rs
> +                                debug!("{json:#?}");
ensure secrets are not logged

2022-05-10 21:30 UTC, sehz commented on src/k8-client/src/cert.rs
> +                            error!("Only Auth provider support for Google Kubernetes Engine (GKE). Please file issue.");
this should return error

2022-05-10 21:30 UTC, sehz commented on src/k8-client/src/cert.rs
> +                    if let Some(auth_provider) = &u.user.auth_provider {
GCP specific token execution should move to `AuthProviderDetail`?

2022-05-11 23:54 UTC, tjtelan commented
The most recent commit isn't compatible w/ fluvio, so I wouldn't merge this yet until that get sorted out

2022-05-12 00:10 UTC, sehz approved these changes
LGTM

2022-05-12 00:11 UTC, sehz commented
bors r+

2022-05-12 00:19 UTC, closed without merging