Remove unused dependencies
infinyon/k8-api pull request #22
Opened 2020-10-15 15:03 UTC by nicholastmosher

This addresses the problems raised in #21 where we want to get rid of our dependency on `rustls`. I ended up using [`cargo-udeps`](https://github.com/est31/cargo-udeps) in order to verify that `rustls` is unused and I found a bunch of other unused dependencies as well. After removing those dependencies, all of the crates continued building with `cargo test --all-features --all-targets`.

2020-10-15 15:22 UTC, sehz commented
Sorry it's probably not obvious how `rustls` is loaded. it is thru third party library `mesalink`.

2020-10-15 15:23 UTC, sehz requested changes

2020-10-15 15:23 UTC, sehz commented on src/k8-client/Cargo.toml
> -curl = { version = "0.4.33", features = ["mesalink"] }
let's put `rustls`  related dependency into feature flag.  We still need to make that work.   Make sure `rustls` feature runs under CI as well

2020-10-15 15:54 UTC, nicholastmosher commented
Regardless, it's become apparent to me that the `rustls` problems we're facing are not actually coming from this crate, they're coming from `fluvio-future`

2020-10-15 15:58 UTC, sehz commented on src/k8-client/Cargo.toml
> -curl = { version = "0.4.33", features = ["mesalink"] }
current configuration works now so let's put all existing `rustls` configuration (minus working in hyper) in feature flag and make sure works in the CI

2020-12-13 17:34 UTC, sehz commented
obsoleted

2020-12-13 17:34 UTC, closed without merging